// Writes the region ids Java's DateTimeFormatter accepts in a zoned
// date-time's brackets: ZoneRulesProvider.getAvailableZoneIds().
//
//   java ZoneIds.java ../../zoneids.go && gofmt -w ../../zoneids.go
import java.io.PrintWriter;
import java.time.zone.ZoneRulesProvider;
import java.util.TreeSet;

public class ZoneIds {
  public static void main(String[] args) throws Exception {
    try (PrintWriter w = new PrintWriter(args[0], "UTF-8")) {
      w.println("// Code generated by testdata/java/ZoneIds.java with Java " + System.getProperty("java.version") + "; DO NOT EDIT.");
      w.println();
      w.println("package buildfile");
      w.println();
      w.println("// zoneIDs are the region ids of Java's time-zone rules.");
      w.println("var zoneIDs = map[string]bool{");
      for (String id : new TreeSet<>(ZoneRulesProvider.getAvailableZoneIds())) {
        w.println("\t\"" + id + "\": true,");
      }
      w.println("}");
    }
  }
}
