name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@v4
      - name: Release with GoReleaser
        run: mise run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
